wallpaper {
    monitor = eDP-1
    path = /home/kst/.config/hypr/wallpapers/laptop.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-3
    path = /home/kst/.config/hypr/wallpapers/monitor.png
    fit_mode = cover
}
